/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Books;
import Books.Add_Book;
import LMS.ImageMagnifier;
import LMS.MainForm;
import static LMS.MainForm.connection;
import static LMS.MainForm.con;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.io.InputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JSpinner;

/**
 *
 * @author Abdul Rehman
 */
public class Edit_Multiple_Books extends javax.swing.JFrame {
    PreparedStatement ps;
    String bookStatus;
    String booksIds = "";
    String imgBookFrontImageLocation = "";
    String imgBookBackImageLocation = "";
    
    /**
     * Creates new form Edit_Book
     */
    public Edit_Multiple_Books() {
        initComponents();
    }
    
    public Edit_Multiple_Books(String[] bookId){
        initComponents();
        {
            txtTitle.setEnabled(false);
            txtAuthor.setEnabled(false);
            txtIsbn.setEnabled(false);
            txtSubject.setEnabled(false);
            txtPublisher.setEnabled(false);
            spnrEdition.setEnabled(false);
            comboBoxLanguage.setEnabled(false);
            txtPrice.setEnabled(false);
            comboBoxCurrency.setEnabled(false);
            txtPlace.setEnabled(false);
            spnrPages.setEnabled(false);
            txtKeyword.setEnabled(false);
            comboBoxGroup.setEnabled(false);
        }
        
        setcbBookGroups();
        {//Setting Languages...
            new Add_Book().setLanguages(comboBoxLanguage);
        }
        this.booksIds = " WHERE id IN (" + bookId[0];
        for (int i=1; i<bookId.length; i++)
            this.booksIds += "," + bookId[i];
        this.booksIds += ")";
    }

    private String setImages(JLabel label) throws NullPointerException{
        String location = "";
        JFileChooser imgFront = new JFileChooser();
        imgFront.showOpenDialog(this);
        
        location = imgFront.getSelectedFile().toString();
        label.setIcon(MainForm.setImage(location, label.getWidth(), label.getHeight()));
        
        return location;
    }
    
    private void setEditable(JTextField txt, JCheckBox cb){
        if (cb.isSelected())
            txt.setEnabled(true);
        else
            txt.setEnabled(false);
    }
    
    private void setEditable(JSpinner spnr, JCheckBox cb){
        if (cb.isSelected())
            spnr.setEnabled(true);
        else
            spnr.setEnabled(false);
    }
    
    private void setEditable(JComboBox ccomboBox, JCheckBox cb){
        if (cb.isSelected())
            ccomboBox.setEnabled(true);
        else
            ccomboBox.setEnabled(false);
    }
    
    private void setcbBookGroups(){
        try {
            connection();
            comboBoxGroup.addItem("None");
            ps = con.prepareStatement("SELECT DISTINCT `group` FROM LMS.BOOK\n" +
                    "WHERE `group` is not null AND `group` != 'none'");
            ResultSet rs = ps.executeQuery();
            while (rs.next()){
                comboBoxGroup.addItem(rs.getString("GROUP"));
            }
            comboBoxGroup.addItem("Custom");
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Add_Book.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtTitle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        spnrEdition = new javax.swing.JSpinner();
        btnCancel = new javax.swing.JButton();
        txtPublisher = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        comboBoxCurrency = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtPlace = new javax.swing.JTextField();
        txtIsbn = new javax.swing.JTextField();
        spnrPages = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        txtAuthor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtKeyword = new javax.swing.JTextField();
        comboBoxLanguage = new javax.swing.JComboBox<>();
        comboBoxGroup = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        cbPages = new javax.swing.JCheckBox();
        cbEdition = new javax.swing.JCheckBox();
        cbSubject = new javax.swing.JCheckBox();
        cbPublisher = new javax.swing.JCheckBox();
        cbLanguage = new javax.swing.JCheckBox();
        cbPrice = new javax.swing.JCheckBox();
        cbPlace = new javax.swing.JCheckBox();
        cbKeyword = new javax.swing.JCheckBox();
        cbCategory = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        btnFrontImageBrowse = new javax.swing.JButton();
        btnBackImageBrowse = new javax.swing.JButton();
        lblBookFrontImage = new javax.swing.JLabel();
        lblBookBackImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Book");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Update Book", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(102, 102, 255))); // NOI18N

        txtTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTitle.setText("Multiple Selection");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Price");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Acc No:");

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblId.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 51, 0));
        lblId.setText("Multiple Selection");

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtPublisher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Publisher");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Title");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Edition");

        txtPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriceKeyTyped(evt);
            }
        });

        comboBoxCurrency.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboBoxCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rs", "$" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Pages");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("ISBN");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Language");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Place");

        txtPlace.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlaceActionPerformed(evt);
            }
        });

        txtIsbn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIsbn.setText("Multiple Selection");
        txtIsbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIsbnKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Author");

        txtAuthor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtAuthor.setText("Mulitple Selection");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Subject:");

        txtSubject.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Keyword");

        txtKeyword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        comboBoxLanguage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        comboBoxGroup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboBoxGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));
        comboBoxGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxGroupActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Category");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Date:");

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDate.setText("Multiple Selection");

        cbPages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPagesActionPerformed(evt);
            }
        });

        cbEdition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEditionActionPerformed(evt);
            }
        });

        cbSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSubjectActionPerformed(evt);
            }
        });

        cbPublisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPublisherActionPerformed(evt);
            }
        });

        cbLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLanguageActionPerformed(evt);
            }
        });

        cbPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPriceActionPerformed(evt);
            }
        });

        cbPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPlaceActionPerformed(evt);
            }
        });

        cbKeyword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKeywordActionPerformed(evt);
            }
        });

        cbCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(48, 48, 48)
                        .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel5)
                        .addGap(37, 37, 37)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(comboBoxCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPrice))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(29, 29, 29)
                        .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel14)
                        .addGap(35, 35, 35)
                        .addComponent(txtPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPlace))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(cbSubject)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel10)
                        .addGap(31, 31, 31)
                        .addComponent(spnrPages, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(cbPages))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28)
                        .addComponent(spnrEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(cbEdition)
                        .addGap(125, 125, 125)
                        .addComponent(jLabel11)
                        .addGap(37, 37, 37)
                        .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(10, 10, 10)
                        .addComponent(txtPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(cbPublisher)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel18)
                        .addGap(10, 10, 10)
                        .addComponent(txtKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbKeyword))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(4, 4, 4)
                        .addComponent(comboBoxLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbLanguage)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel6)
                                .addGap(10, 10, 10)
                                .addComponent(comboBoxGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCategory))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2))
                    .addComponent(lblId)
                    .addComponent(jLabel1)
                    .addComponent(lblDate))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cbPrice)
                        .addComponent(comboBoxCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel14))
                    .addComponent(txtPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPlace))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel17))
                    .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSubject)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(spnrPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(cbPages)))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9))
                    .addComponent(txtPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(cbPublisher))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel18))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(cbKeyword)
                        .addComponent(txtKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(spnrEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(cbEdition))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel11))
                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel12))
                            .addComponent(comboBoxLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel6))
                            .addComponent(comboBoxGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbLanguage))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancel)
                            .addComponent(btnUpdate)))
                    .addComponent(cbCategory))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Book Pic", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(102, 102, 255))); // NOI18N

        btnFrontImageBrowse.setText("Browse");
        btnFrontImageBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrontImageBrowseActionPerformed(evt);
            }
        });

        btnBackImageBrowse.setText("Browse");
        btnBackImageBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackImageBrowseActionPerformed(evt);
            }
        });

        lblBookFrontImage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBookFrontImage.setText("          Front");
        lblBookFrontImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblBookFrontImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBookFrontImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBookFrontImageMouseClicked(evt);
            }
        });

        lblBookBackImage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBookBackImage.setText("          Back");
        lblBookBackImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblBookBackImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBookBackImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBookBackImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBookBackImage, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBackImageBrowse)
                                .addGap(24, 24, 24))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblBookFrontImage, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnFrontImageBrowse)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBookFrontImage, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFrontImageBrowse)
                .addGap(25, 25, 25)
                .addComponent(lblBookBackImage, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBackImageBrowse)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(270, 270, 270))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(269, 269, 269))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try{
            InputStream frontImage=null, backImage=null;
            String frontImageQuery = "", backImageQuery = "";
            try{
                frontImage = new FileInputStream(imgBookFrontImageLocation);
                frontImageQuery = ", frontImage = " + frontImage;
            }catch(FileNotFoundException e){}
            
            try{
                backImage = new FileInputStream(imgBookBackImageLocation);
                backImageQuery = ", backImage = " + backImage;
            }catch(FileNotFoundException e){}
            
            StringBuilder sb = new StringBuilder();
            
            if (cbSubject.isSelected()){sb.append("subject = '").append(txtSubject.getText()).append("'");}
            if (cbPublisher.isSelected()){sb.append(", publisher = '").append(txtPublisher.getText()).append("'");}
            if (cbEdition.isSelected()){sb.append(", edition = '").append(spnrEdition.getValue()).append("'");}
            try{if (cbLanguage.isSelected()){sb.append(", language = '").append(comboBoxLanguage.getSelectedItem()).append("'");}}catch(NullPointerException e){}
            if (cbPrice.isSelected()){sb.append(", price = '").append(txtPrice.getText()).append("', Currency = '").append(comboBoxCurrency.getSelectedItem()).append("'");}
            if (cbPlace.isSelected()){sb.append(", place = '").append(txtPlace.getText()).append("'");}
            if (cbPages.isSelected()){sb.append(", pages = '").append(spnrPages.getValue()).append("'");}
            if (cbKeyword.isSelected()){sb.append(", keyword = '").append(txtKeyword.getText()).append("'");}
            if (cbCategory.isSelected()){sb.append(", `group` = '").append(comboBoxGroup.getSelectedItem()).append("'");}
            
            if (!(cbSubject.isSelected())){sb.deleteCharAt(0);}
            
            String query = "UPDATE book SET " + sb + frontImageQuery + " " + backImageQuery + booksIds;
            
            MainForm.connection();
            
            ps = MainForm.con.prepareStatement(query);
            
            if (!ps.execute()){
                JOptionPane.showMessageDialog(null, txtTitle.getText()+" has been Updated Sucessfully.", "Update Book", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
            else
            JOptionPane.showMessageDialog(null, txtTitle.getText()+"could not be Updated.", "Update Book", JOptionPane.ERROR_MESSAGE);
        }
        catch(SQLException | ClassNotFoundException e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(Add_Book.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        imgBookFrontImageLocation = "";
        imgBookBackImageLocation = "";
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyTyped
        if (!Character.isDigit(evt.getKeyChar()))
        evt.consume();
    }//GEN-LAST:event_txtPriceKeyTyped

    private void txtIsbnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIsbnKeyTyped
        if(!Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txtIsbnKeyTyped

    private void comboBoxGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxGroupActionPerformed
        try{
            if (comboBoxGroup.getSelectedItem().equals("Custom")){
            comboBoxGroup.setEditable(true);
            comboBoxGroup.setSelectedItem(null);
            }else
            comboBoxGroup.setEditable(false);
        }catch(NullPointerException e){}
    }//GEN-LAST:event_comboBoxGroupActionPerformed

    private void btnFrontImageBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrontImageBrowseActionPerformed
        try{imgBookFrontImageLocation = setImages(lblBookFrontImage);}
        catch(NullPointerException e){
            lblBookFrontImage.setIcon(null); 
            lblBookFrontImage.setText("       Front");
            imgBookFrontImageLocation = "";
        }
    }//GEN-LAST:event_btnFrontImageBrowseActionPerformed

    private void btnBackImageBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackImageBrowseActionPerformed
        try{imgBookBackImageLocation = setImages(lblBookBackImage);}
        catch(NullPointerException e){
            lblBookBackImage.setIcon(null); 
            lblBookBackImage.setText("       Back");
            imgBookBackImageLocation = "";
        }
    }//GEN-LAST:event_btnBackImageBrowseActionPerformed

    private void lblBookFrontImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBookFrontImageMouseClicked
        new ImageMagnifier(true, lblId.getText()).setVisible(true);
    }//GEN-LAST:event_lblBookFrontImageMouseClicked

    private void lblBookBackImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBookBackImageMouseClicked
        new ImageMagnifier(false, lblId.getText()).setVisible(true);
    }//GEN-LAST:event_lblBookBackImageMouseClicked

    private void cbSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSubjectActionPerformed
        setEditable(txtSubject, cbSubject);
    }//GEN-LAST:event_cbSubjectActionPerformed

    private void cbPublisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPublisherActionPerformed
        setEditable(txtPublisher, cbPublisher);
    }//GEN-LAST:event_cbPublisherActionPerformed

    private void cbEditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEditionActionPerformed
        setEditable(spnrEdition, cbEdition);
    }//GEN-LAST:event_cbEditionActionPerformed

    private void cbLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLanguageActionPerformed
        setEditable(comboBoxLanguage, cbLanguage);
    }//GEN-LAST:event_cbLanguageActionPerformed

    private void cbPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPriceActionPerformed
        setEditable(txtPrice, cbPrice);
        setEditable(comboBoxCurrency, cbPrice);
    }//GEN-LAST:event_cbPriceActionPerformed

    private void txtPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlaceActionPerformed
        setEditable(txtPlace, cbPlace);
    }//GEN-LAST:event_txtPlaceActionPerformed

    private void cbPagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPagesActionPerformed
        setEditable(spnrPages, cbPages);
    }//GEN-LAST:event_cbPagesActionPerformed

    private void cbKeywordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKeywordActionPerformed
        setEditable(txtKeyword, cbKeyword);
    }//GEN-LAST:event_cbKeywordActionPerformed

    private void cbCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoryActionPerformed
        setEditable(comboBoxGroup, cbCategory);
    }//GEN-LAST:event_cbCategoryActionPerformed

    private void cbPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPlaceActionPerformed
        setEditable(txtPlace, cbPlace);
    }//GEN-LAST:event_cbPlaceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_Multiple_Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_Multiple_Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_Multiple_Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_Multiple_Books.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_Multiple_Books().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackImageBrowse;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFrontImageBrowse;
    public javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox cbCategory;
    private javax.swing.JCheckBox cbEdition;
    private javax.swing.JCheckBox cbKeyword;
    private javax.swing.JCheckBox cbLanguage;
    private javax.swing.JCheckBox cbPages;
    private javax.swing.JCheckBox cbPlace;
    private javax.swing.JCheckBox cbPrice;
    private javax.swing.JCheckBox cbPublisher;
    private javax.swing.JCheckBox cbSubject;
    private javax.swing.JComboBox<String> comboBoxCurrency;
    private javax.swing.JComboBox<String> comboBoxGroup;
    private javax.swing.JComboBox<String> comboBoxLanguage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    static javax.swing.JLabel lblBookBackImage;
    static javax.swing.JLabel lblBookFrontImage;
    private javax.swing.JLabel lblDate;
    public javax.swing.JLabel lblId;
    private javax.swing.JSpinner spnrEdition;
    private javax.swing.JSpinner spnrPages;
    public javax.swing.JTextField txtAuthor;
    public javax.swing.JTextField txtIsbn;
    public javax.swing.JTextField txtKeyword;
    public javax.swing.JTextField txtPlace;
    public javax.swing.JTextField txtPrice;
    public javax.swing.JTextField txtPublisher;
    public javax.swing.JTextField txtSubject;
    public javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
