/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Books;
import LMS.ImageMagnifier;
import LMS.MainForm;
import LMS.NewException;
import static LMS.MainForm.connection;
import static LMS.MainForm.con;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.io.InputStream;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import javax.swing.JLabel;
import java.awt.FileDialog;

/**
 *
 * @author Abdul Rehman
 */
public class Edit_Book extends javax.swing.JFrame {
    PreparedStatement ps;
    String bookStatus;
    
    String imgBookFrontImageLocation = "";
    String imgBookBackImageLocation = "";
    
    /**
     * Creates new form Edit_Book
     */
    public Edit_Book() {
        initComponents();
    }
    
    public Edit_Book(String bookId){
        initComponents();
        setcbBookGroups();
        try {
            connection();
            ps = con.prepareStatement("SELECT * FROM book WHERE id = '" + bookId + "'");
            ResultSet rs = ps.executeQuery();
            if (rs.next()){
                lblId.setText(bookId);
                txtTitle.setText(rs.getString("title"));
                txtAuthor.setText(rs.getString("author"));
                txtSubject.setText(rs.getString("subject"));
                txtPublisher.setText(rs.getString("Publisher"));
                try{spnrEdition.setValue(Integer.parseInt(rs.getString("edition")));}catch(NumberFormatException e){}
                
                txtPrice.setText(rs.getString("Price"));
                cbCurrency.setSelectedItem(rs.getString("Currency"));
                txtPlace.setText(rs.getString("Place"));
                spnrPages.setValue(Integer.parseInt(rs.getString("pages")));
                txtKeyword.setText(rs.getString("keyword"));
                txtIsbn.setText(rs.getString("isbn"));
                
                if (rs.getString("status").equals("Private"))
                    checkBoxCantIssue.setSelected(true);
                
                cbGroup.setSelectedItem(rs.getString("group"));
                lblDate.setText(rs.getString("date"));
                
                try{lblBookFrontImage.setIcon(MainForm.setImage(rs.getBytes("frontImage"), lblBookFrontImage.getWidth(), lblBookFrontImage.getHeight()));}
                catch(NullPointerException e){}
                
                try{lblBookBackImage.setIcon(MainForm.setImage(rs.getBytes("backImage"), lblBookBackImage.getWidth(), lblBookBackImage.getHeight()));}
                catch(NullPointerException e){}
                
                {//Setting Languages....
                    new Add_Book().setLanguages(cbLanguage);
                    cbLanguage.setSelectedItem(rs.getString("Language"));
                }
                
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Edit_Book.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }

    private String setImages(JLabel label) throws NullPointerException{
        String location = "";
        FileDialog imgFront = new FileDialog(this, "Select Book Picture", FileDialog.LOAD);
        imgFront.setVisible(true);
        
        location = imgFront.getDirectory() + imgFront.getFile();
        label.setIcon(MainForm.setImage(location, label.getWidth(), label.getHeight()));
        
        return location;
    }
    
    private void setcbBookGroups(){
        try {
            connection();
            cbGroup.addItem("None");
            ps = con.prepareStatement("SELECT DISTINCT `group` FROM BOOK\n" +
                    "WHERE `group` is not null AND `group` != 'none'");
            ResultSet rs = ps.executeQuery();
            while (rs.next()){
                cbGroup.addItem(rs.getString("GROUP"));
            }
            cbGroup.addItem("Custom");
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Add_Book.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtTitle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        spnrEdition = new javax.swing.JSpinner();
        btnCancel = new javax.swing.JButton();
        txtPublisher = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        cbCurrency = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtPlace = new javax.swing.JTextField();
        txtIsbn = new javax.swing.JTextField();
        spnrPages = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        txtAuthor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtKeyword = new javax.swing.JTextField();
        cbLanguage = new javax.swing.JComboBox<>();
        cbGroup = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        checkBoxCantIssue = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        btnFrontImageBrowse = new javax.swing.JButton();
        btnBackImageBrowse = new javax.swing.JButton();
        lblBookFrontImage = new javax.swing.JLabel();
        lblBookBackImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Book");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Update Book", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(102, 102, 255))); // NOI18N

        txtTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Price");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Acc No:");

        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdd.setText("Update");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblId.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 51, 0));
        lblId.setText("ID:");

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtPublisher.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Publisher");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Title");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Edition");

        txtPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPriceKeyTyped(evt);
            }
        });

        cbCurrency.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbCurrency.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rs", "$" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Pages");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("ISBN");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Language");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Place");

        txtPlace.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtIsbn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIsbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIsbnKeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Author");

        txtAuthor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Subject:");

        txtSubject.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Keyword");

        txtKeyword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cbLanguage.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbLanguage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLanguageActionPerformed(evt);
            }
        });

        cbGroup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGroupActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Category");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Date:");

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDate.setText("Date");

        checkBoxCantIssue.setBackground(new java.awt.Color(204, 204, 204));
        checkBoxCantIssue.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkBoxCantIssue.setText("Do Not Issue");
        checkBoxCantIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxCantIssueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(10, 10, 10)
                        .addComponent(txtPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel18)
                        .addGap(10, 10, 10)
                        .addComponent(txtKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28)
                        .addComponent(spnrEdition, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)
                        .addComponent(jLabel11)
                        .addGap(37, 37, 37)
                        .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(4, 4, 4)
                        .addComponent(cbLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel6)
                        .addGap(10, 10, 10)
                        .addComponent(cbGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(checkBoxCantIssue)
                        .addGap(240, 240, 240)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(37, 37, 37)
                                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(cbCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(35, 35, 35)
                                        .addComponent(txtPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(31, 31, 31)
                                        .addComponent(spnrPages, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lblId))
                    .addComponent(jLabel1)
                    .addComponent(lblDate))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cbCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel3)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel16))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel14))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel17))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(spnrPages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(txtAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(txtSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel18))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(spnrEdition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel11))
                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12))
                    .addComponent(cbLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6))
                    .addComponent(cbGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnCancel)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(checkBoxCantIssue)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Book Pic", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(102, 102, 255))); // NOI18N

        btnFrontImageBrowse.setText("Browse");
        btnFrontImageBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFrontImageBrowseActionPerformed(evt);
            }
        });

        btnBackImageBrowse.setText("Browse");
        btnBackImageBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackImageBrowseActionPerformed(evt);
            }
        });

        lblBookFrontImage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBookFrontImage.setText("         Front");
        lblBookFrontImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblBookFrontImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBookFrontImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBookFrontImageMouseClicked(evt);
            }
        });

        lblBookBackImage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblBookBackImage.setText("          Back");
        lblBookBackImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblBookBackImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBookBackImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBookBackImageMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBookFrontImage, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblBookBackImage, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnFrontImageBrowse)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBackImageBrowse)
                .addGap(34, 34, 34))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBookFrontImage, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFrontImageBrowse)
                .addGap(35, 35, 35)
                .addComponent(lblBookBackImage, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBackImageBrowse)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(259, 259, 259))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try{
            InputStream frontImage=null, backImage=null;
            String frontImageQuery = "", backImageQuery = "";
            boolean isFrontImageChoosen = false, isBackImageChoosen = false;
            int numberOfPictures = 13;
            try{
                frontImage = new FileInputStream(imgBookFrontImageLocation);
                frontImageQuery = ", frontImage=?";
                isFrontImageChoosen = true;
            }catch(FileNotFoundException e){}
            
            try{
                backImage = new FileInputStream(imgBookBackImageLocation);
                backImageQuery = ", backImage=?";
                isBackImageChoosen = true;
            }catch(FileNotFoundException e){}
            
            MainForm.connection();
            ps = MainForm.con.prepareStatement("UPDATE book SET title=?, author=?, subject=?, publisher=?, edition=?, language=?, price=?, currency=?,"
                    + " place=?, pages=?, keyword=?, ISBN=?, `group`=? "+frontImageQuery+" "+backImageQuery+" WHERE id = " + lblId.getText());
            ps.setString(1, txtTitle.getText());  if (txtTitle.getText().equals("")) throw new NewException("Book Title Must be Provided.");
            ps.setString(2, txtAuthor.getText()); if (txtAuthor.getText().equals("")) throw new NewException("Book Author Must be Provided.");
            ps.setString(3, txtSubject.getText());
            ps.setString(4, txtPublisher.getText());
            ps.setString(5, spnrEdition.getValue().toString());
            try{ps.setString(6, cbLanguage.getSelectedItem().toString());}catch(NullPointerException | SQLException e){ps.setString(6, "");}
            ps.setString(7, (txtPrice.getText().equals("") ? "0" : txtPrice.getText()));
            try{ps.setString(8, cbCurrency.getSelectedItem().toString());}catch(NullPointerException ex){ps.setString(8, "Rs");}
            ps.setString(9, txtPlace.getText());
            ps.setString(10, spnrPages.getValue().toString());
            ps.setString(11, txtKeyword.getText());
            ps.setString(12, txtIsbn.getText());
            try{ps.setString(13, cbGroup.getSelectedItem().toString());}catch (NullPointerException | SQLException e){ps.setString(13, "");}
            
            if (isFrontImageChoosen)
                ps.setBlob(++numberOfPictures, frontImage);
            
            if (isBackImageChoosen)
                ps.setBlob(++numberOfPictures, backImage);
            
            if (!ps.execute()){
                if (checkBoxCantIssueStateChanged){
                    ps = con.prepareStatement("SELECT `STATUS` FROM BOOK WHERE ID = '"+lblId.getText()+"'");
                    ResultSet rs = ps.executeQuery();
                    if (rs.next()){
                        if ((rs.getString("status").equals("Available") || rs.getString("status").startsWith("Reserved")) && 
                                checkBoxCantIssue.isSelected()){
                            ps = con.prepareStatement("UPDATE BOOK SET `STATUS` = 'Private' WHERE id = '"+lblId.getText()+"'");
                            ps.execute();
                        }
                        else if (rs.getString("status").equals("Private") && !checkBoxCantIssue.isSelected()){
                            ps = con.prepareStatement("UPDATE BOOK SET `STATUS` = 'Available' WHERE id = '"+lblId.getText()+"'");
                            ps.execute();
                        }
                        else
                            JOptionPane.showMessageDialog(this, "Can't Change the Status of Book", "Can't Issue Settings", JOptionPane.ERROR_MESSAGE);
                    }
                }
                JOptionPane.showMessageDialog(null, "Book \""+txtTitle.getText()+"\" has been Updated Sucessfully.", "Update Book", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
            else
            JOptionPane.showMessageDialog(null, txtTitle.getText()+"could not be Updated.", "Update Book", JOptionPane.ERROR_MESSAGE);
        }
        catch(SQLException | ClassNotFoundException | NewException e)
        {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(Add_Book.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        imgBookFrontImageLocation = "";
        imgBookBackImageLocation = "";
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtPriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyTyped
        if (!Character.isDigit(evt.getKeyChar()))
        evt.consume();
    }//GEN-LAST:event_txtPriceKeyTyped

    private void txtIsbnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIsbnKeyTyped
        if(!Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txtIsbnKeyTyped

    private void cbGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGroupActionPerformed
        try{
            if (cbGroup.getSelectedItem().equals("Custom")){
            cbGroup.setEditable(true);
            cbGroup.setSelectedItem(null);
            }else
            cbGroup.setEditable(false);
        }catch(NullPointerException e){}
    }//GEN-LAST:event_cbGroupActionPerformed

    private void btnFrontImageBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFrontImageBrowseActionPerformed
        try{imgBookFrontImageLocation = setImages(lblBookFrontImage);}
        catch(NullPointerException e){
            lblBookFrontImage.setIcon(null); 
            lblBookFrontImage.setText("       Front");
            imgBookFrontImageLocation = "";
        }
    }//GEN-LAST:event_btnFrontImageBrowseActionPerformed

    private void btnBackImageBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackImageBrowseActionPerformed
        try{imgBookBackImageLocation = setImages(lblBookBackImage);}
        catch(NullPointerException e){
            lblBookBackImage.setIcon(null); 
            lblBookBackImage.setText("       Back");
            imgBookBackImageLocation = "";
        }
    }//GEN-LAST:event_btnBackImageBrowseActionPerformed

    private void lblBookFrontImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBookFrontImageMouseClicked
        new ImageMagnifier(true, lblId.getText()).setVisible(true);
    }//GEN-LAST:event_lblBookFrontImageMouseClicked

    private void lblBookBackImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBookBackImageMouseClicked
        new ImageMagnifier(false, lblId.getText()).setVisible(true);
    }//GEN-LAST:event_lblBookBackImageMouseClicked

    private void cbLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLanguageActionPerformed
        try{
            if (cbLanguage.getSelectedItem().toString().equals("Custom")){
                cbLanguage.setEditable(true);
                cbLanguage.setSelectedItem(null);
            }else
                cbLanguage.setEditable(false);
        }catch(NullPointerException e){}
    }//GEN-LAST:event_cbLanguageActionPerformed

    boolean checkBoxCantIssueStateChanged = false;
    private void checkBoxCantIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxCantIssueActionPerformed
        if (checkBoxCantIssueStateChanged)
            checkBoxCantIssueStateChanged = false;
        else if (!checkBoxCantIssueStateChanged)
            checkBoxCantIssueStateChanged = true;
        System.out.println(checkBoxCantIssueStateChanged);
    }//GEN-LAST:event_checkBoxCantIssueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_Book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBackImageBrowse;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFrontImageBrowse;
    private javax.swing.JComboBox<String> cbCurrency;
    private javax.swing.JComboBox<String> cbGroup;
    private javax.swing.JComboBox<String> cbLanguage;
    private javax.swing.JCheckBox checkBoxCantIssue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    static javax.swing.JLabel lblBookBackImage;
    static javax.swing.JLabel lblBookFrontImage;
    private javax.swing.JLabel lblDate;
    public javax.swing.JLabel lblId;
    private javax.swing.JSpinner spnrEdition;
    private javax.swing.JSpinner spnrPages;
    public javax.swing.JTextField txtAuthor;
    public javax.swing.JTextField txtIsbn;
    public javax.swing.JTextField txtKeyword;
    public javax.swing.JTextField txtPlace;
    public javax.swing.JTextField txtPrice;
    public javax.swing.JTextField txtPublisher;
    public javax.swing.JTextField txtSubject;
    public javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
