/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Settings;
import static LMS.MainForm.connection;
import static LMS.MainForm.con;
import LMS.NewException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JButton;

/**
 *
 * @author Abdul Rehman
 */
public class General_Settings extends javax.swing.JFrame {
    PreparedStatement ps;
    /**
     * Creates new form General_Settings
     */
    public General_Settings() {
        initComponents();
        try {
            setRightOptionsForGeneralSettings();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(General_Settings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public final void setRightOptionsForGeneralSettings() throws SQLException, ClassNotFoundException{
        connection();
        ps = con.prepareStatement("SELECT id, `SET`, `value`, set2, set3 FROM GENERAL_SETTINGS");
        ResultSet rs = ps.executeQuery();
        while (rs.next()){
            //Settings Double Click to Return Book on Statistics Table...
            if (rs.getInt("id") == 1)
                btnDoubleCLickToReturnBook.setText(rs.getString("set"));
            else if (rs.getInt("id") == 2){
                btnFineOnLateReturn.setText(rs.getString("set"));
                tfFineOnLateReturn.setText(rs.getString("value"));
                tfFineOnLateReturnDays.setText(rs.getString("set3"));
                comboBoxLateBookReturnFrequencyOfFine.setSelectedItem(rs.getString("set2"));
            }
            else if (rs.getInt("id") == 3){
                btn.setText(rs.getString("set"));
                tf.setText(rs.getString("value"));
                comboBox.setSelectedItem(rs.getString("set2"));
            }
            else if (rs.getInt("id") == 4){
                btnDoubleCLickToReturnBook1.setText(rs.getString("set"));
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlDoubleClick = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnDoubleCLickToReturnBook = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnDoubleCLickToReturnBook1 = new javax.swing.JButton();
        pnlLateBookReturn = new javax.swing.JPanel();
        btnFineOnLateReturn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfFineOnLateReturn = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        comboBoxLateBookReturnFrequencyOfFine = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        tfFineOnLateReturnDays = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pnlLateFine = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tf = new javax.swing.JTextField();
        comboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("General Settings");
        setResizable(false);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("Double Click Settings");

        btnDoubleCLickToReturnBook.setText("OFF");
        btnDoubleCLickToReturnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoubleCLickToReturnBookActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Double Click on Statistics Table to Return Book");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Double Click on Current Fine Table to Pay Fine");

        btnDoubleCLickToReturnBook1.setText("OFF");
        btnDoubleCLickToReturnBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoubleCLickToReturnBook1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDoubleClickLayout = new javax.swing.GroupLayout(pnlDoubleClick);
        pnlDoubleClick.setLayout(pnlDoubleClickLayout);
        pnlDoubleClickLayout.setHorizontalGroup(
            pnlDoubleClickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoubleClickLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlDoubleClickLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDoubleClickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDoubleClickLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDoubleCLickToReturnBook, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDoubleClickLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(btnDoubleCLickToReturnBook1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlDoubleClickLayout.setVerticalGroup(
            pnlDoubleClickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoubleClickLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(pnlDoubleClickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoubleCLickToReturnBook))
                .addGap(61, 61, 61)
                .addGroup(pnlDoubleClickLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoubleCLickToReturnBook1))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Double Click", pnlDoubleClick);

        btnFineOnLateReturn.setText("ON");
        btnFineOnLateReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFineOnLateReturnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 153));
        jLabel2.setText("Fine On Late Return Of Book");

        tfFineOnLateReturn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfFineOnLateReturn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfFineOnLateReturnKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 255));
        jLabel8.setText("Amount: ");

        comboBoxLateBookReturnFrequencyOfFine.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboBoxLateBookReturnFrequencyOfFine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RS/Day", "Once" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 255));
        jLabel9.setText("Last Date Should Be After");

        tfFineOnLateReturnDays.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfFineOnLateReturnDays.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfFineOnLateReturnDaysKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 0));
        jLabel3.setText("Days");

        javax.swing.GroupLayout pnlLateBookReturnLayout = new javax.swing.GroupLayout(pnlLateBookReturn);
        pnlLateBookReturn.setLayout(pnlLateBookReturnLayout);
        pnlLateBookReturnLayout.setHorizontalGroup(
            pnlLateBookReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLateBookReturnLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(pnlLateBookReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(pnlLateBookReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlLateBookReturnLayout.createSequentialGroup()
                            .addComponent(tfFineOnLateReturnDays, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26))
                        .addGroup(pnlLateBookReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlLateBookReturnLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfFineOnLateReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBoxLateBookReturnFrequencyOfFine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(108, 108, 108))
            .addGroup(pnlLateBookReturnLayout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(btnFineOnLateReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlLateBookReturnLayout.setVerticalGroup(
            pnlLateBookReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLateBookReturnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(38, 38, 38)
                .addGroup(pnlLateBookReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFineOnLateReturn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(comboBoxLateBookReturnFrequencyOfFine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlLateBookReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFineOnLateReturnDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(btnFineOnLateReturn)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Late Book Return", pnlLateBookReturn);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 153));
        jLabel4.setText("Late Paying of Fine");

        btn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn.setText("OFF");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 255));
        jLabel5.setText("Amount: ");

        tf.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfKeyTyped(evt);
            }
        });

        comboBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RS/Day", "Once" }));

        javax.swing.GroupLayout pnlLateFineLayout = new javax.swing.GroupLayout(pnlLateFine);
        pnlLateFine.setLayout(pnlLateFineLayout);
        pnlLateFineLayout.setHorizontalGroup(
            pnlLateFineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLateFineLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207))
            .addGroup(pnlLateFineLayout.createSequentialGroup()
                .addGroup(pnlLateFineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLateFineLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLateFineLayout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel4)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        pnlLateFineLayout.setVerticalGroup(
            pnlLateFineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLateFineLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(pnlLateFineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btn)
                .addGap(68, 68, 68))
        );

        jTabbedPane1.addTab("Late Fine", pnlLateFine);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void toggleButtons(JButton btn){
        String s = btn.getText();
        if(s.equals("OFF"))
            btn.setText("ON");
        else if (s.equals("ON"))
            btn.setText("OFF");
    }
    private void btnDoubleCLickToReturnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoubleCLickToReturnBookActionPerformed
        toggleButtons(btnDoubleCLickToReturnBook);
        
        {//Saving the Settings...
            try {
                connection();
                ps = con.prepareStatement("DELETE FROM GENERAL_SETTINGS WHERE ID = 1");
                ps.execute();

                ps = con.prepareStatement("INSERT INTO GENERAL_SETTINGS\n" +
                    "SET ID = 1,\n" +
                    "`SET` = '"+btnDoubleCLickToReturnBook.getText()+"',\n" +
                    "`DESCRIPTION` = 'When turned On then You can double click to return table at Statistics to return a book'");
                if (!ps.execute()){
                    LMS.All_Information.doReturnBookOnDoubleClick = btnDoubleCLickToReturnBook.getText().equals("ON");
                }
                else
                    JOptionPane.showMessageDialog(this, "Unable to save settings", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(General_Settings.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDoubleCLickToReturnBookActionPerformed

    private void btnFineOnLateReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFineOnLateReturnActionPerformed
        try {
            String tfValue = tfFineOnLateReturn.getText();
            connection();
            if (tfValue.equals(""))
                throw new NewException("Please Specify the Fine Amount Per Day!");
            toggleButtons(btnFineOnLateReturn);
            ps = con.prepareStatement("DELETE FROM GENERAL_SETTINGS WHERE ID = 2");
            ps.execute();
            
            ps = con.prepareStatement("INSERT INTO GENERAL_SETTINGS\n" +
                                        "SET ID = 2,\n" +
                                        "`SET` = '"+btnFineOnLateReturn.getText()+"',\n" +
                                        "`SET2` = '"+comboBoxLateBookReturnFrequencyOfFine.getSelectedItem()+"',\n" +
                                        "`SET3` = '"+tfFineOnLateReturnDays.getText()+"',\n" +
                                        "`VALUE` = '"+tfFineOnLateReturn.getText()+"',\n" +
                                        "`DESCRIPTION` = 'When Someone Does Not Return Book on Time then he or she is "
                    + "charged fine According to the price per day you save And the book is returned with fine.'");
            ps.execute();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(General_Settings.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(NewException e){JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_btnFineOnLateReturnActionPerformed

    private void tfFineOnLateReturnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFineOnLateReturnKeyTyped
        if (!Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_tfFineOnLateReturnKeyTyped

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        try {
            String tfValue = tf.getText();
            connection();
            if (tfValue.equals(""))
                throw new NewException("Please Specify the Fine Amount Per Day!");
            toggleButtons(btn);
            ps = con.prepareStatement("DELETE FROM GENERAL_SETTINGS WHERE ID = 3");
            ps.execute();
            
            ps = con.prepareStatement("INSERT INTO GENERAL_SETTINGS\n" +
                                        "SET ID = 3,\n" +
                                        "`SET` = '"+btn.getText()+"',\n" +
                                        "`SET2` = '"+comboBox.getSelectedItem()+"',\n" +
                                        "`VALUE` = '"+tfValue+"',\n" +
                                        "`DESCRIPTION` = \"When Member doesn't pay fine on time then he has to pay late fine"
                                                + " which is the specified on value column of general settings and "
                                                + "which can be charged as daily or once according to librarian wish.\"");
            ps.execute();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(General_Settings.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch(NewException e){JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);}
    }//GEN-LAST:event_btnActionPerformed

    private void tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfKeyTyped
        if (!Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_tfKeyTyped

    private void tfFineOnLateReturnDaysKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFineOnLateReturnDaysKeyTyped
        if (!Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_tfFineOnLateReturnDaysKeyTyped

    private void btnDoubleCLickToReturnBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoubleCLickToReturnBook1ActionPerformed
        toggleButtons(btnDoubleCLickToReturnBook1);
        
        {//Saving the Settings...
            try {
                connection();
                ps = con.prepareStatement("DELETE FROM GENERAL_SETTINGS WHERE ID = 4");
                ps.execute();

                ps = con.prepareStatement("INSERT INTO GENERAL_SETTINGS\n" +
                    "SET ID = 4,\n" +
                    "`SET` = '"+btnDoubleCLickToReturnBook1.getText()+"',\n" +
                    "`DESCRIPTION` = 'This one is the setting for returning fine. When you double click on current fine table"
                            + "then this will target to pay fine function. '");
                if (!ps.execute()){
                    LMS.All_Information.doPayFineOnDoubleClick = btnDoubleCLickToReturnBook1.getText().equals("ON");
                }
                else
                    JOptionPane.showMessageDialog(this, "Unable to save settings", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(General_Settings.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDoubleCLickToReturnBook1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(General_Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(General_Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(General_Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(General_Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new General_Settings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btnDoubleCLickToReturnBook;
    private javax.swing.JButton btnDoubleCLickToReturnBook1;
    private javax.swing.JButton btnFineOnLateReturn;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JComboBox<String> comboBoxLateBookReturnFrequencyOfFine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnlDoubleClick;
    private javax.swing.JPanel pnlLateBookReturn;
    private javax.swing.JPanel pnlLateFine;
    private javax.swing.JTextField tf;
    private javax.swing.JTextField tfFineOnLateReturn;
    private javax.swing.JTextField tfFineOnLateReturnDays;
    // End of variables declaration//GEN-END:variables
}
