/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmailPackage;
import javax.swing.JToggleButton;
import java.awt.Color;
import static LMS.MainForm.connection;
import static LMS.MainForm.con;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import Abdul_Rehmancom.company.EncryptPassword;
import LMS.NewException;
import com.sun.mail.util.MailConnectException;
import java.sql.ResultSet;
import javax.mail.AuthenticationFailedException;
import javax.mail.MessagingException;
import java.awt.Font;

/**
 *
 * @author Abdul Rehman
 */
public class EmailSettings extends javax.swing.JFrame {
    PreparedStatement ps;
    String emailAddress;
    /**
     * Creates new form EmailSettings
     */
    public EmailSettings() {
        initComponents();
        setSettings();
    }
    
    private void setSettings(){
        EncryptPassword ep = new EncryptPassword();
        try {
            connection();
            ps = con.prepareStatement("SELECT ID, EMAIL, PASSWORD, AUTOEMAIL1 as a1, AUTOEMAIL2 as a2, AUTOEMAIL3 as a3, AUTOEMAIL4 as a4 FROM Email_Settings "
                    + "WHERE ID = 1 OR ID = 2");
            ResultSet rs = ps.executeQuery();
            while (rs.next()){
                if (rs.getString("ID").equals("1")){
                    if (rs.getString("a1").equals("ON")){togleBtn1.setSelected(true); togleBtn1.setText("ON");}
                    if (rs.getString("a2").equals("ON")){togleBtn2.setSelected(true); togleBtn2.setText("ON");}
                    if (rs.getString("a3").equals("ON")){togleBtn3.setSelected(true); togleBtn3.setText("ON");}
                    if (rs.getString("a4").equals("ON")){togleBtn4.setSelected(true); togleBtn4.setText("ON");}
                }else if (rs.getString("ID").equals("2")){
                    emailAddress = ep.Encrypt(rs.getString("Email"));
                    tfEmail.setText(emailAddress);
                }
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(EmailSettings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        tfEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        checkBoxShowPassword = new javax.swing.JCheckBox();
        pfPassword = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        togleBtn1 = new javax.swing.JToggleButton();
        togleBtn2 = new javax.swing.JToggleButton();
        jLabel6 = new javax.swing.JLabel();
        togleBtn3 = new javax.swing.JToggleButton();
        togleBtn4 = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Email Settings");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("Email");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Set Default Email", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 51, 255))); // NOI18N

        tfEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Emal Address:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Password:");

        checkBoxShowPassword.setBackground(new java.awt.Color(255, 255, 255));
        checkBoxShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxShowPasswordActionPerformed(evt);
            }
        });

        pfPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(checkBoxShowPassword))
                    .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(checkBoxShowPassword))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Automatic Emails", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 51, 255))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Book Issue Email:");
        jLabel4.setToolTipText("Automatic Email goes when ever Library Member Issues a Book.");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Book Return Email:");
        jLabel5.setToolTipText("Automatic Email goes When Ever Member Returns a Book.");

        togleBtn1.setBackground(new java.awt.Color(255, 255, 153));
        togleBtn1.setText("OFF");
        togleBtn1.setToolTipText("Automatic Email goes when ever Library Member Issues a Book.");
        togleBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togleBtn1ActionPerformed(evt);
            }
        });

        togleBtn2.setBackground(new java.awt.Color(255, 255, 153));
        togleBtn2.setText("OFF");
        togleBtn2.setToolTipText("Automatic Email goes When Ever Member Returns a Book.");
        togleBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togleBtn2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Email At Book Return Date:");
        jLabel6.setToolTipText("Automatic Email Goes When Ever Member Does Not Returns a Book ON Return Date");

        togleBtn3.setBackground(new java.awt.Color(255, 255, 153));
        togleBtn3.setText("OFF");
        togleBtn3.setToolTipText("Automatic Email Goes When Ever Member Does Not Returns a Book ON Return Date");
        togleBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togleBtn3ActionPerformed(evt);
            }
        });

        togleBtn4.setBackground(new java.awt.Color(255, 255, 153));
        togleBtn4.setText("OFF");
        togleBtn4.setToolTipText("Automatic Email Goes When Ever Member Does Not Returns a Book ON Return Date");
        togleBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togleBtn4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Email After Return Date");
        jLabel7.setToolTipText("Automatic Email Goes When Ever Member Does Not Returns a Book ON Return Date");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(togleBtn3)
                    .addComponent(togleBtn2)
                    .addComponent(togleBtn1)
                    .addComponent(togleBtn4))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(togleBtn1))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(togleBtn2)
                    .addComponent(jLabel5))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(togleBtn3)
                    .addComponent(jLabel6))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(togleBtn4)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSave.setBackground(new java.awt.Color(204, 204, 255));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(51, 0, 204));
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSave)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void togleBtnSettingOnAndOff(JToggleButton btn){
        if (btn.isSelected()){
            btn.setText("ON");
            btn.setBackground(Color.YELLOW);
        }
        else{
            btn.setText("OFF");
            btn.setBackground(new Color(255,255,153));
        }
    }
    private void togleBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togleBtn1ActionPerformed
//        Indicating weather toggle Button is on or off by colors. red shows on and yellow shows off.
        togleBtnSettingOnAndOff(togleBtn1);
    }//GEN-LAST:event_togleBtn1ActionPerformed

    private void checkBoxShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxShowPasswordActionPerformed
        if (checkBoxShowPassword.isSelected())
            pfPassword.setEchoChar((char)0);
        else
            pfPassword.setEchoChar('*');
    }//GEN-LAST:event_checkBoxShowPasswordActionPerformed

    private void togleBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togleBtn2ActionPerformed
        togleBtnSettingOnAndOff(togleBtn2);
    }//GEN-LAST:event_togleBtn2ActionPerformed

    private void togleBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togleBtn3ActionPerformed
        togleBtnSettingOnAndOff(togleBtn3);
    }//GEN-LAST:event_togleBtn3ActionPerformed

    private void togleBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togleBtn4ActionPerformed
        togleBtnSettingOnAndOff(togleBtn4);
    }//GEN-LAST:event_togleBtn4ActionPerformed

    private void deleteEmailAddressFromSettings() throws SQLException, ClassNotFoundException{
        connection();
        PreparedStatement ps3 = con.prepareStatement("DELETE FROM email_settings where ID = 2");
        ps3.execute();
    }
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        EncryptPassword ep = new EncryptPassword();
        String email = tfEmail.getText();
        String password = String.valueOf(pfPassword.getPassword());
        
        try {
            connection();
            
            {//Deleting Old Settings so that new settings can be saved.
                PreparedStatement ps3 = con.prepareStatement("DELETE FROM email_settings where ID = 1");
                ps3.execute();
            }
            
            ps = con.prepareStatement("INSERT INTO email_settings (autoEmail1, `autoemail2`, autoemail3, autoemail4, ID)\n" +
                "VALUES (?, ?, ?, ?, ?)");
            ps.setString(1, ((togleBtn1.isSelected()) ? "ON" : "OFF"));
            ps.setString(2, ((togleBtn2.isSelected()) ? "ON" : "OFF"));
            ps.setString(3, ((togleBtn3.isSelected()) ? "ON" : "OFF"));
            ps.setString(4, ((togleBtn4.isSelected()) ? "ON" : "OFF"));
            ps.setString(5, "1");
            ps.execute();
            
            if (!password.equals("")){
                String subject = "LMS Default Email Address.";
                String content = "<h2>This Email Address has been Set as Default Email Address Of LMS (Library Management System)</h2>";
                new SendEmail().sendEmail(email, password, email, subject, content);
                
                {//Deleting Old table so that new settings can be saved.
                    deleteEmailAddressFromSettings();
                }
                
                PreparedStatement ps2 = con.prepareStatement("INSERT INTO email_settings (Email, `password`, ID)\n" +
                    "VALUES (?, ?, ?)");
                ps2.setString(1, ep.Encrypt(email));
                ps2.setString(2, ep.Encrypt(String.valueOf(password)));
                ps2.setString(3, "2");  
                ps2.execute();
            }
            else if (email.equals("") && password.equals("")){
                deleteEmailAddressFromSettings();
            }

            new AutomaticEmail().sendEmailAtReturnDate();
            new AutomaticEmail().sendEmailAfterReturnDate();
            JOptionPane.showMessageDialog(this, "Settings Saved", "Emails", JOptionPane.INFORMATION_MESSAGE);
            this.dispose();
            
        } catch (MailConnectException e){
            JOptionPane.showMessageDialog(this, "Failed!\nNo Internet Connection.\nCan't verify new email", "Email", JOptionPane.ERROR_MESSAGE);
        }
        catch (AuthenticationFailedException e){
            String msg = "Failed!\nWrong Email Address or Password. \nIf you get this Error Continuously then go to your Email Address Settings and Turn on the Less secure App"
                    + " Settings then try Again.";
            JOptionPane.showMessageDialog(this, msg, "Email", JOptionPane.ERROR_MESSAGE);
        }
        catch (MessagingException ex) {
            JOptionPane.showMessageDialog(this, ex, "Email", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(EmailSettings.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Failed to Save Settings", "Emails", JOptionPane.INFORMATION_MESSAGE);
            //Logger.getLogger(EmailSettings.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmailSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmailSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmailSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmailSettings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new EmailSettings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox checkBoxShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JToggleButton togleBtn1;
    private javax.swing.JToggleButton togleBtn2;
    private javax.swing.JToggleButton togleBtn3;
    private javax.swing.JToggleButton togleBtn4;
    // End of variables declaration//GEN-END:variables
}
