/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LMS;
import Settings.Deciding_First_Page_To_Open;
import Settings.Recover_Password_By_Email;
import Settings.Recover_Password_By_Question;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Cursor;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import Abdul_Rehmancom.company.EncryptPassword;

/**
 *
 * @author Abdul Rehman Lashari
 */
public class Login extends javax.swing.JFrame {
    PreparedStatement ps;
    int count = 0;
    
    /**
     * Creates new form Login
     */
/**    
* Unused Functions...
*      SendingPicturetoDatabase();
*      SetPic();
*/
            
    
    public Login() {
        initComponents();
        tfPassword.setEchoChar((char)0);
        
        lblForgotPassword.setVisible(false);
    }
    
    public String focusLostLogic(String txtFieldString, String hint) {
        if (txtFieldString.equals("")) {
            txtFieldString = hint;
        }
        return txtFieldString;
    }

    public String focusGainedLogic(String txtFieldString, String hint) {
        if (txtFieldString.equals(hint)) {
            txtFieldString = "";
        }
        return txtFieldString;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        pnlComponent = new javax.swing.JPanel();
        tfPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblForgotPassword = new javax.swing.JLabel();
        lblWrongPassword = new javax.swing.JLabel();
        IBAName = new javax.swing.JLabel();
        IBAName1 = new javax.swing.JLabel();
        checkBoxShowPassword = new javax.swing.JCheckBox();
        MainLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        pnlComponent.setBackground(new java.awt.Color(102, 153, 255));
        pnlComponent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlComponent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfPassword.setText("Enter Password");
        tfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPasswordFocusLost(evt);
            }
        });
        tfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfPasswordKeyReleased(evt);
            }
        });
        pnlComponent.add(tfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 214, 32));

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlComponent.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 130, 34));

        lblForgotPassword.setText("<html><h5><a href = \"\">Forgot Password");
        lblForgotPassword.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblForgotPasswordMouseMoved(evt);
            }
        });
        lblForgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblForgotPasswordMouseClicked(evt);
            }
        });
        pnlComponent.add(lblForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 580, -1, -1));

        lblWrongPassword.setBackground(new java.awt.Color(51, 51, 255));
        lblWrongPassword.setForeground(new java.awt.Color(255, 0, 51));
        pnlComponent.add(lblWrongPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 145, 17));

        IBAName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        IBAName.setForeground(new java.awt.Color(51, 0, 255));
        IBAName.setText("Naushahro Feroze");
        pnlComponent.add(IBAName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, -1, -1));

        IBAName1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        IBAName1.setForeground(new java.awt.Color(51, 0, 255));
        IBAName1.setText("INSTITUTE OF BUSINESS ADMINISTRATION COMMUNITY COLLEGE");
        pnlComponent.add(IBAName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        checkBoxShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxShowPasswordActionPerformed(evt);
            }
        });
        pnlComponent.add(checkBoxShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 30, 30));

        MainLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsUsed/IBA.jpg"))); // NOI18N
        MainLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlComponent.add(MainLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 610));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlComponent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlComponent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblForgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotPasswordMouseClicked
        try {
            MainForm.connection();
            ps = MainForm.con.prepareStatement("SELECT email, question, answer FROM password WHERE id =1");
            ResultSet rs = ps.executeQuery();
            if (rs.next()){
                EncryptPassword ep = new EncryptPassword();
                String email = null;
                String question = null;
                String answer = null;
                try{email = ep.Encrypt(rs.getString("email"));}catch(NullPointerException e){}
                try{question = ep.Encrypt(rs.getString("question"));}catch(NullPointerException e){}
                try{answer = ep.Encrypt(rs.getString("answer"));}catch(NullPointerException e){}
                if (!(email == null)){
                    Recover_Password_By_Email r = new Recover_Password_By_Email();
                    r.Email_Receiver(email, answer);
                    r.setVisible(true);
                }
                else if (!(question == null)){
                    Recover_Password_By_Question r = new Recover_Password_By_Question();
                    r.Question_Answer_Receiver(question, answer);
                    r.setVisible(true);
                }
                else {
                    JOptionPane.showMessageDialog(rootPane, "No any Recovery action is Set!\n Now Contact Developer", 
                            "Password Recovery", JOptionPane.ERROR_MESSAGE);
                }
            }else JOptionPane.showMessageDialog(rootPane, "Sorry any Error Occoured!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblForgotPasswordMouseClicked

    private void tfPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusGained
        tfPassword.setText(focusGainedLogic(String.valueOf(tfPassword.getPassword()), "Enter Password"));
        tfPassword.setEchoChar('*'); 
        checkBoxShowPassword.setSelected(false);
    }//GEN-LAST:event_tfPasswordFocusGained

    private void tfPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPasswordFocusLost
        String password = String.valueOf(tfPassword.getPassword());
        if(password.equals(""))
            tfPassword.setEchoChar((char)0);
        tfPassword.setText(focusLostLogic(password, "Enter Password"));
    }//GEN-LAST:event_tfPasswordFocusLost

    private void loginLogic(){
        String password = "";
        {   //Getting password from database and saving in password variable...for future use...
            try {
                MainForm.connection();
                ps = MainForm.con.prepareStatement("SELECT password FROM password WHERE id = 1");
                ResultSet rs = ps.executeQuery();
                if (rs.next()){
                    Abdul_Rehmancom.company.EncryptPassword ep = new Abdul_Rehmancom.company.EncryptPassword();
                    password = ep.Encrypt(rs.getString("password"));
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Password not found in Database");
                }
            } catch (SQLException | ClassNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        if (String.valueOf(tfPassword.getPassword()).equals(password)){
            new Deciding_First_Page_To_Open().chooseFile();
            this.dispose();
        }
        else{
            lblWrongPassword.setText("Wrong Password!");
            count++;
            if (count == 3)
                lblForgotPassword.setVisible(true);
        }
    }
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        checkBoxShowPassword.setSelected(false);
        tfPassword.setEchoChar('*');
        loginLogic();    
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblForgotPasswordMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotPasswordMouseMoved
        Cursor cur = new Cursor(Cursor.HAND_CURSOR);
        lblForgotPassword.setCursor(cur);
    }//GEN-LAST:event_lblForgotPasswordMouseMoved

    private void tfPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPasswordKeyReleased
        if (evt.getKeyChar() == java.awt.event.KeyEvent.VK_ENTER){
            loginLogic();
        }
        else
            lblWrongPassword.setText(null);
    }//GEN-LAST:event_tfPasswordKeyReleased

    private void checkBoxShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxShowPasswordActionPerformed
        if (checkBoxShowPassword.isSelected())
            tfPassword.setEchoChar((char)0);
        else 
            tfPassword.setEchoChar('*');
    }//GEN-LAST:event_checkBoxShowPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IBAName;
    private javax.swing.JLabel IBAName1;
    private javax.swing.JLabel MainLabel;
    private javax.swing.JButton btnLogin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkBoxShowPassword;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblForgotPassword;
    private javax.swing.JLabel lblWrongPassword;
    private javax.swing.JPanel pnlComponent;
    private javax.swing.JPasswordField tfPassword;
    // End of variables declaration//GEN-END:variables
}
