/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LMS;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.util.Vector;
import static LMS.MainForm.connection;
import static LMS.MainForm.con;
import javax.swing.JOptionPane;
/**
 *
 * @author Abdul Rehman
 */
public class ReservationOfBook extends javax.swing.JFrame {
    PreparedStatement ps;
    DefaultTableModel tm;
    /**
     * Creates new form ReservationOfBook
     */
    public ReservationOfBook() {
        initComponents();
        tm = (DefaultTableModel) tblReservationData.getModel();
        settingData();
    }
    
    private void settingData(){
        try {
            MainForm.connection();
            tm.setRowCount(0);
            ps = MainForm.con.prepareStatement("SELECT b.id as bid, b.title, b.author, R.STUDENT_id as sid, sd.first_name, sd.last_name, sd.group, b.status FROM LMS.RESERVE_BOOK R\n" +
                    "LEFT JOIN lms.student_data sd ON sd.id = student_id\n" +
                    "LEFT JOIN lms.book b ON b.id = book_id");
            ResultSet rs = ps.executeQuery();
            while (rs.next()){
                Vector v = new Vector();
                v.add(rs.getString("sid"));
                v.add(rs.getString("First_Name") + " " + rs.getString("Last_Name"));
                v.add(rs.getString("group"));
                v.add(rs.getString("bid"));
                v.add(rs.getString("title"));
                v.add(rs.getString("author"));
                v.add(statusChanger(rs.getString("status")));
                tm.addRow(v);
            }
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ReservationOfBook.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private String statusChanger(String status){
        return status.substring(0, 8).equals("Reserved") ? "Available" : status;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservationData = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnIssueBook = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Reservation Of Books");

        tblReservationData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblReservationData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member ID", "Name", "Category", "Accession No", "Title", "Author", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReservationData.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblReservationData);

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnIssueBook.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnIssueBook.setText("Issue Book");
        btnIssueBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1013, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(btnDelete)
                                .addGap(18, 18, 18)
                                .addComponent(btnIssueBook)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnIssueBook))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public boolean deleteReservation(String studentId, String bookId) throws SQLException, ClassNotFoundException{
        connection();
        ps = con.prepareStatement("DELETE FROM LMS.RESERVE_BOOK WHERE student_id = '"+studentId+
                        "' AND book_id = '"+bookId+"'");
        return !ps.execute();
    }
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try{
            if (tblReservationData.getSelectionModel().isSelectionEmpty())
                throw new NewException("Nothing is Selected to Delete.");
            for (int selectedRows : tblReservationData.getSelectedRows()){
                connection();
                ps = con.prepareStatement("SELECT book_id FROM lms.issue_book WHERE book_id = '"+tm.getValueAt(selectedRows, 3)+"'");
                ResultSet rs = ps.executeQuery();
                if (!rs.next()){
                    ps = con.prepareStatement("UPDATE LMS.BOOK SET `STATUS` = 'Available' WHERE ID = '"+tm.getValueAt(selectedRows, 3)+"'");
                    ps.execute();
                }
                
                if (deleteReservation(tm.getValueAt(selectedRows, NORMAL).toString(), tm.getValueAt(selectedRows, 3).toString()) ){
                    JOptionPane.showMessageDialog(this, "Reservation is Deleted.", "Delete Reservation", JOptionPane.INFORMATION_MESSAGE);
                    settingData();
                }
                    
            }
        } catch (SQLException | ClassNotFoundException | NewException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            //Logger.getLogger(ReservationOfBook.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnIssueBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueBookActionPerformed
        if (!tblReservationData.getSelectionModel().isSelectionEmpty())
            new IssueBook(tm.getValueAt(tblReservationData.getSelectedRow(), NORMAL).toString(), 
                tm.getValueAt(tblReservationData.getSelectedRow(), 3).toString()).setVisible(true);
        else
            JOptionPane.showMessageDialog(this, "First Select Any Record From Table", "Issue Book", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_btnIssueBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReservationOfBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReservationOfBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReservationOfBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReservationOfBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReservationOfBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnIssueBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReservationData;
    // End of variables declaration//GEN-END:variables
}
